version: '3'
services:
  puppeteer-renderer-1:
    image: ghcr.io/zenato/puppeteer-renderer:latest
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage --disable-extensions --no-sandbox --headless --single-process
  puppeteer-renderer-2:
    image: ghcr.io/zenato/puppeteer-renderer:latest
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage --disable-extensions --no-sandbox --headless --single-process
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - puppeteer-renderer-1
      - puppeteer-renderer-2
