version: '3'
services:
  puppeteer-renderer-1:
    image: ghcr.io/zenato/puppeteer-renderer:latest
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage --disable-extensions --no-sandbox --headless --single-process
    restart: always

  puppeteer-renderer-2:
    image: ghcr.io/zenato/puppeteer-renderer:latest
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage --disable-extensions --no-sandbox --headless --single-process
    restart: always

  puppeteer-renderer-3:
    image: ghcr.io/zenato/puppeteer-renderer:latest
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage --disable-extensions --no-sandbox --headless --single-process
    restart: always

  puppeteer-renderer-4:
    image: ghcr.io/zenato/puppeteer-renderer:latest
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage --disable-extensions --no-sandbox --headless --single-process
    restart: always

  puppeteer-renderer-5:
    image: ghcr.io/zenato/puppeteer-renderer:latest
    environment:
      - PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-gpu --disable-dev-shm-usage --disable-extensions --no-sandbox --headless --single-process
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - puppeteer-renderer-1
      - puppeteer-renderer-2
      - puppeteer-renderer-3
      - puppeteer-renderer-4
      - puppeteer-renderer-5
    restart: always
